### ISSUE TITLE
New version of garbage collection

### ISSUE THREAD

**Issue by grm** [amaximus/garbage-collection-card#10]
Hello,

It seems you does not support the last version of garbage collection (which has been updated).
I have this in my configuration :

```
garbage_collection:
  sensors:
  - name: Menager
    frequency: "weekly"
    verbose_state: True
    verbose_format: "Dans {days} jours"
    collection_days:
    - tue
    - fri
  - name: Recyclable
    frequency: "weekly"
    verbose_state: True
    verbose_format: "Dans {days} jours"
    collection_days:
    - wed
```

But in the UI, I still have the words in english, as shown here (using lovelace) :
<img width="393" alt="Screenshot 2019-11-03 at 16 49 56" src="https://user-images.githubusercontent.com/70435/68087885-07a0c800-fe5a-11e9-9437-f58429030995.png">

The card configuration in use is : 
```
            - type: custom:garbage-collection-card
              entity: sensor.menager
              icon_color: blue
              hide_date: true
            - type: custom:garbage-collection-card
              entity: sensor.recyclable
              icon_color: green
              hide_date: true
```

Am I missing something ?

Thx,
Grm
