### ISSUE TITLE
Pick-up due tomorrow now shows 'Tomorrow 1'

### ISSUE THREAD

**Issue by Scoff123** [amaximus/garbage-collection-card#103]
I've just noticed that because our recycling and refuse are both due for pick-up tomorrow, although my card is correctly showing my 'due_1_color', instead of just showing the due_txt of 'Tomorrow' like it normally does, it shows 'Tomorrow 1' therefore it appears to be including the state of my sensor.recycling (which has a current state of 1) as well as the due_txt?

I am running version 1.22.2 of the card, and
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230110.0 - latest

My card code:
````
type: custom:garbage-collection-card
entity: sensor.recycling
icon_color: green
icon_size: 35px
due_color: red
due_1_color: yellow
due_text: false
hide_on_click: false
````

**Comment by amaximus** [comment]
Could you please provide a snapshot on sensor.recycling from Developer Tools -> States where I can see the sensor state and its attributes. Thanks.

**Comment by Scoff123** [comment]
Sure thing, here you go:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/96984460/215802586-ad7c19c2-a7a1-4a29-8b0c-65390627ebdb.png">

My second sensor is also showing 'Tomorrow 1' and here is the state of that one:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/96984460/215802932-f8e198d5-14b9-4770-bedf-a04ed1914044.png">

My 3rd sensor is actually showing correctly, but that one isn't due for pick up for 2 days, however it correctly shows: 02/02/2023 in 2 days as the due_txt. Here is the state of that sensor:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/96984460/215803411-47495cad-552b-4399-a579-b2eaca069b13.png">

and a snapshot of how all 3 currently show:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/96984460/215803539-a49a60de-3940-4171-a2bb-e1b57156aae9.png">

**Comment by Scoff123** [comment]
Just to add to this - as of today, the card now shows as follows:

<img width="120" alt="image" src="https://user-images.githubusercontent.com/96984460/216022834-8496fd21-e081-465c-a5fc-1b39de5a195c.png">

**Comment by amaximus** [comment]
Thanks. I found the error, I'll fix it later today.

**Comment by Scoff123** [comment]
Great, thank you 👍

**Comment by amaximus** [comment]
I pushed a release (1.22.3) fixing this issue.
Please update the card and get back to me with results.

I saw that you are using ```due_txt: false```. Please note that this will make the normal "_date_ in [1|2] days" displayed when due date is today or tomorrow. To have 'Today' and 'Tomorrow' displayed please use ```due_txt: true```

**Comment by Scoff123** [comment]
Thanks. I've downloaded 1.22.3 and reloaded, cleared browser cache and even restarted HA, however nothing seems to have changed - the card is still displaying exactly as it was before. I've tried deleting the card and creating it fresh, and re-downloading the new version a second time, but nothing looks any different with the card? Also, changing between ```due_txt: false``` and ```due_txt: true``` makes no difference to the appearance of the due text strangely?

My full card config:
```
type: vertical-stack
cards:
  - type: custom:garbage-collection-card
    entity: sensor.recycling
    icon_color: green
    icon_size: 35px
    due_color: red
    due_1_color: yellow
    due_text: true
    hide_on_click: false
  - type: custom:garbage-collection-card
    entity: sensor.big_bin
    icon_color: grey
    icon_size: 35px
    due_color: red
    due_1_color: yellow
    due_text: true
    hide_on_click: false
  - type: custom:garbage-collection-card
    entity: sensor.garden_waste
    icon_color: green
    icon_size: 35px
    due_color: red
    due_1_color: yellow
    due_text: true
    hide_on_click: false
```

and current display using 1.22.3

<img width="112" alt="image" src="https://user-images.githubusercontent.com/96984460/216131443-d9b45a05-6e51-4ddd-b758-10c45228c989.png">
