### ISSUE TITLE
[BUG] hide_on_click stopped working after version 1.22.1

### ISSUE THREAD

**Issue by Floix** [amaximus/garbage-collection-card#108]
**Describe the bug**
The hide_on_click setting is not working anymore since version 1.22.1

**To Reproduce**
Simple garbage collection setting:
```yaml
 type: custom:garbage-collection-card
 entity: sensor.garbage_waste
 icon_size: 35px
 due_color: '#ff5e04'
 due_1_color: '#ff5e04'
 icon_color: '#5e5a5a'
 hide_date: false
 hide_on_click: true
```

hide_on_click is set to true (even though that's default), but no matter how ofter I click on due day or day before --> it won't hide anymore.

**Expected behavior**
Garbage card hidden.

**Screenshots**
[Example image, click on second card, no reaction](https://ibb.co/k2h7TS3)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.22.3
 - Browser: chrome (110.0.5481.180) & firefox (109.0.1)
 - Browser language: German
 - Home-Assistant version 2023.3.2

**Additional context**
