### ISSUE TITLE
Verbose state doesn't show up

### ISSUE THREAD

**Issue by codypet** [amaximus/garbage-collection-card#14]
When I use the card verbose state doesn't show up.  If I use a regular glance card, I have no problem.
Regular Glance Card:
![image](https://user-images.githubusercontent.com/17790157/71053734-6a55d680-211d-11ea-9113-3430ea169435.png)
Config:
```
type: glance
entities:
  - entity: sensor.trash
  - entity: sensor.recycling

```
Garbage Collection Card:
![image](https://user-images.githubusercontent.com/17790157/71053749-7a6db600-211d-11ea-8d97-1e15e6e660d1.png)
Config:
```
type: horizontal-stack
cards:
  - entity: sensor.trash
    icon_size: 35px
    type: 'custom:garbage-collection-card'
  - entity: sensor.recycling
    icon_size: 35px
    type: 'custom:garbage-collection-card'
```
