### ISSUE TITLE
Sensors 'undefined'

### ISSUE THREAD

**Issue by aegjoyce** [amaximus/garbage-collection-card#19]
Today I've noticed that the lovelace card, whilst showing the names and icons of the sensors it represents, shows 'undefined' instead of the due date for garbage collection.

Looking in 'states' the sensors are working correctly and as anticipated. I have verbose switched on.

Tried reverting to 1.2.1 but this has not fixed it. I think the problem has started since HA 104.2 was released.

My previously working config is otherwise unchanged. (HassOS 3.8, HA 104.2)

**Comment by aegjoyce** [comment]
Update: it works fine if I set verbose to false, but not if verbose is set to true

**Comment by codypet** [comment]
Same situation for me.  I had accidentally put this on the Integration page, but I'll provide it here and close that thread.
**Describe the bug**
The card shows up as undefined and rebooting the pi or restarting Hass doesn't help

**Configuration**
```
garbage_collection:
  sensors:
  - name: "Trash"
    frequency: "weekly"
    collection_days:
    - tue
    exclude_dates:
    - '2019-12-25'
    verbose_state: True
  - name: "Recycling"
    frequency: "weekly"
    icon_normal: mdi:recycle
    collection_days:
    - fri
    exclude_dates:
    - '2019-12-25'
    verbose_state: True
```

**Error log/debug information**
Nothing Unusual
```
2020-01-18 20:47:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
**Screenshots**
![image](https://user-images.githubusercontent.com/17790157/72673435-71337a00-3a38-11ea-9d72-4f604037e0d0.png)

**Version**
Home assistant 104.2 
Garbage Collection 2.13
