### ISSUE TITLE
Setup for specific dates

### ISSUE THREAD

**Issue by pichlerralf** [amaximus/garbage-collection-card#20]
Hello,

hope i'm correct to paste this here:
i am getting errors regarding incorrect configs if i setup a garbage on specific dates only.
Did not find anything on the docs to have this explained.

Config is:
```
  - name: Paper # specific dates
    collection_days: "sat"
    include_dates:
    - '2020-03-05'
    - '2020-04-02'
    - '2020-05-07'
    - '2020-06-05'
    - '2020-07-02'
```

Thanks for your help in advance!
P.s. I already use your tool for some garbages - great, thanks a lot!
/ Ralf
