### ISSUE TITLE
Lovelace not loading when I use a stacked card

### ISSUE THREAD

**Issue by bschatzow** [amaximus/garbage-collection-card#24]
```
-
        cards:
          - entity: sensor.trash
            icon_color: brown
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.recycle
            icon_color: red
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.branches
            icon_color: green
            icon_size: 35px
            type: 'custom:garbage-collection-card'
          - entity: sensor.yard_waste
            icon_color: green
            icon_size: 35px
            type: 'custom:garbage-collection-card'
        type: vertical-stack
```
It does work correctly when 1 individually. I tried loading the same three and they failed.

```
-
        entity: sensor.trash
        icon_color: brown
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - 
        entity: sensor.recycle
        icon_color: red
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - 
        entity: sensor.branches
        icon_color: green
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - 
        entity: sensor.yard_waste
        icon_color: green
        icon_size: 35px
        type: 'custom:garbage-collection-card'
  ```
