### ISSUE TITLE
Slowing down entire Lovelace interface in HomeAssistant 0.115.2

### ISSUE THREAD

**Issue by charlyr82** [amaximus/garbage-collection-card#45]
I have three garbage collection sensors, and adding them to a view in my dashboard using this custom card slows my entire Lovelace interface down to a point where it is practically non-responsive.

The cards do load, but take a significant amount of time, and then any interaction with the Lovelace interface takes approximately 10 seconds to respond.

Opening the developer tools in chrome and looking at the console I am presented with a warning:
`[Deprecation] Synchronous XMLHttpRequest on garbage-collection-card.js:281 the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help, check https://xhr.spec.whatwg.org/.`

I don’t use `verbose_state: true` as I use the numeric state for some automations.

This card was working perfectly for me in 0.114, I don’t know if some of the optimising that has been going on recently within HomeAssistant has caused this to happen?

**Comment by amaximus** [comment]
Could you please let me know if your garbage collection cards are included into some other cards (e.g. vertical-stack)?

I have seven garbage collection cards for testing (each for one weekday) without having them included into any other type of cards and they are not causing high load or similar issues.

I'm assuming some interference with some other card.

**Comment by charlyr82** [comment]
In my original configuration they were included in their own view on one of my dashboards. For testing purposes I have created a new empty dashboard, and copied just that view to it, so the code for the entire dashboard is below:

```
title: Test Dashboard
views:
  - badges: []
    cards:
      - entity: sensor.general_waste
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - entity: sensor.recycling
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - entity: sensor.garden_waste
        icon_size: 35px
        type: 'custom:garbage-collection-card'
    icon: 'mdi:trash-can'
    panel: false
    path: bins
    title: Bins
```
This test dashboard has decreased the delay that I am noticing, however there is definitely still a delay present. As this is the only view in this dashboard, I have been testing by switching between different dashboards in the sidebar. Switching between any of my dashboards other than this one is pretty much instant (always less than 1 second). Switching from any dashboard to this one is the same, however switching from this test dashboard to any of my others (whilst very occasionally is instant) normally takes 5 seconds or more (from the new dashboard gaining the background highlight in the sidebar to the dashboard actually loading in the main area of the page).
