### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'states' of undefined

### ISSUE THREAD

**Issue by robearlam** [amaximus/garbage-collection-card#46]
I'm getting a strange error, in come cases when using this card. I have it working fine on one panel but not on another. I'm trying to use vertically stacked inside [vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card), like so:

```
- type: 'custom:vertical-stack-in-card'
        cards:
            show_icon: false
            show_state: true
            type: glance
          - type: 'custom:garbage-collection-card'
            entity: sensor.recycling_collection
            icon_size: 35px
            icon_color: green
            hide_date: true
          - type: 'custom:garbage-collection-card'
            entity: sensor.rubbish_collection
            icon_color: '#0561ba'
            hide_date: true
```

The strange thing is, it works in the Preview modal, but then when I accept changes it's not displayed in the real LoveLace view, and there is the following console error reported:

```
Uncaught (in promise) TypeError: Cannot read property 'states' of undefined
    at garbage-collection-card.js:59
    at Array.forEach (<anonymous>)
    at HTMLElement._getAttributes (garbage-collection-card.js:54)
    at HTMLElement.set hass [as hass] (garbage-collection-card.js:263)
    at HTMLElement.createCardElement (vertical-stack-in-card.js:95)
    at vertical-stack-in-card.js:25
    at Array.map (<anonymous>)
    at HTMLElement.renderCard (vertical-stack-in-card.js:25)
    at HTMLElement.setConfig (vertical-stack-in-card.js:20)
```

**Comment by amaximus** [comment]
As a test could you please try moving the custom garbage collection card out of the vertical-stack-in-card card?

I can of course add a check before line 59 to see if hass is defined, but since noone reported similar issue while the card is used by many, I rather suspect that this is caused by some interference with the vertical-stack-in-card. That's why my above test proposal to exclude this case.
You may also try to flush your browser cache and reload the page once you applied the changes from Preview modal (seems you are not using the yaml mode, but do edits within the UI).

Looking forward to hear about your test results.

**Comment by robearlam** [comment]
Yeah the card works fine outside of the custom-vertical-stack card, it seems like a clash between the two.

Once changes are applied using hard refresh (no cache) the card sometimes shows, sometimes gives the error listed above.

It's a strange one.

Full yaml for the card is:

```
type: vertical-stack
cards:
  - type: markdown
    content: '# Home'
    style: |
      ha-card {
        text-align: center;
        background-color: transparent !important;
        box-shadow: none !important;
      }
  - type: weather-forecast
    entity: weather.home
  - type: 'custom:vertical-stack-in-card'
    cards:
      - type: 'custom:garbage-collection-card'
        entity: sensor.recycling_collection
        icon_size: 35px
        icon_color: green
        hide_date: true
      - type: 'custom:garbage-collection-card'
        entity: sensor.rubbish_collection
        icon_color: '#0561ba'
        hide_date: true
```

**Comment by danielbrunt57** [comment]
Your code...
```
type: vertical-stack
cards:
  - type: markdown
    content: '# Home'
    style: |
      ha-card {
        text-align: center;
        background-color: transparent !important;
        box-shadow: none !important;
      }
  - type: weather-forecast
    entity: weather.norton_court
  - type: 'custom:vertical-stack-in-card'
    cards:
      - type: 'custom:garbage-collection-card'
        entity: sensor.waste
        icon_size: 35px
        icon_color: green
      - type: 'custom:garbage-collection-card'
        entity: sensor.recycling
        icon_color: '#0561ba'

```
...does not work for me either.

I'm using this code...
```
type: vertical-stack
cards:
  - type: 'custom:garbage-collection-card'
    entity: sensor.waste
    icon_color: black
    due_color: red
    due_1_color: purple
    due_txt: true
  - type: 'custom:garbage-collection-card'
    entity: sensor.recycling
    icon_color: black
    due_color: red
    due_1_color: blue
    due_txt: true
```
and it works in Firefox but starting yesterday it stopped working in Chrome.
