### ISSUE TITLE
due_color is not being applied when days=0

### ISSUE THREAD

**Issue by danielbrunt57** [amaximus/garbage-collection-card#61]
**Describe the bug**
I've just noticed that due_color is not working.  The due_1_color is still being applied when number of days is 0
**To Reproduce**
```
type: vertical-stack
cards:
  - type: 'custom:garbage-collection-card'
    entity: sensor.waste
    icon_color: black
    due_color: red
    due_1_color: green
    due_txt: true
  - type: 'custom:garbage-collection-card'
    entity: sensor.recycling
    icon_color: black
    due_color: red
    due_1_color: blue
    due_txt: true
```

**Expected behavior**
I expect to see the red!

**Screenshots**
![image](https://user-images.githubusercontent.com/49846893/102380572-ec6d1b00-3f7c-11eb-9ab3-80df255ad773.png)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.16.2
 - Browser: Firefox
 - Browser language: en-ca
 - Home Assistant Version: 2012.12.0
