### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by turbotopo** [amaximus/garbage-collection-card#65]
please update your installation guide.
we cannot add resources to configuration.yaml.

Please also show how to add the card to the ui.

thanks for your nice project ;-)

**Comment by amaximus** [comment]
Added some instructions for non-yaml configuration.

Please check and get back to me with results.

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by kizio1000** [comment]
Still can't get card working. 
"No card type configured"
When added resource as below in Configuration->Lovelace dashboards->Resources->Add resource:

/hacsfiles/garbage-collection-card/garbage-collection-card.js

**Comment by amaximus** [comment]
Can you post the card definition from your dashboard?

**Comment by kizio1000** [comment]
It works only for one entity with code below:

`type: custom:garbage-collection-card
entity: sensor.selektywne
icon_size: 35px
icon_color: green`

If tried to use two or more entietes with code below then it is giving error
![obraz_2021-01-22_190133](https://user-images.githubusercontent.com/76654878/105527625-3e276480-5ce4-11eb-9935-18c327c99f00.png)

**Comment by amaximus** [comment]
Please note that your indentation is wrong, one level down it should be 2 chars. Setting it on UI it still ends up in yaml. Something like:

```
cards:
  - type: custom:garbage-collection-card
     entity: ....
     ....
  - type: custom:garbage-collection-card
     entity: ....
     ....
```
