### ISSUE TITLE
[BUG] No card type found

### ISSUE THREAD

**Issue by greghesp** [amaximus/garbage-collection-card#70]
Not sure what the issue is here.  I've gone into Hacs -> Frontend -and added the Garbage Collection Card.
I've then gone to Lovelace Dashboards -> Resources and added `/hacsfiles/garbage-collection-card/garbage-collection-card.js`

HA has been rebooted and the manual card I am trying to add is below

```
cards:
  - type: 'custom:garbage-collection-card'
    entity: sensor.garden_2
    icon_size: 35px
    icon_color: green
    hide_date: true
  - type: 'custom:garbage-collection-card'
    entity: sensor.waste_2
    hide_before: 4
    icon_color: '#0561ba'

```
