### ISSUE TITLE
Missing views?

### ISSUE THREAD

**Issue by Rincovanderbeek** [amaximus/garbage-collection-card#71]
Hi,
I installed conform the manual, however it state's missing views.

Any Idea what I'm doing wrong?

configuration.yaml:
```
sensor:
  - platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: epe
    postcode: 8171BC
    streetnumber: 16
    dateformat: "%A %d %B %Y"
    locale: "nl"
    timespanindays: 365

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}
```

ui-lovelace.yaml:
```
cards:
  - type: custom:garbage-collection-card
    entity: sensor.afvalinfo_next_trash_type_and_date
    icon_size: 35px
    icon_color: green
    hide_date: true
  - type: custom:garbage-collection-card
    entity: sensor.afvalinfo_next_trash_type_and_date
    hide_before: 4
    icon_color: '#0561ba'
```
