### ISSUE TITLE
How do I unhide a garbage collection entity if I accidentally clicked it?

### ISSUE THREAD

**Issue by trackzero** [amaximus/garbage-collection-card#94]
Hey there, not sure what I'm missing; but I accidentally clicked my trash-day card and it disappeared.  I went in and added hide_on_click: false but that doesn't seem to be enough to bring back the missing sensor.  Then I went in through developer tools and set last_collection to null; it blinks in, gets overwritten with today's date immediately.

**Comment by trackzero** [comment]
Nevermind, figured it out.  Went to services and ran:
```
service: garbage_collection.collect_garbage
data:
  entity_id: sensor.trash
  last_collection: 2022-04-06T10:54:00.000Z
```
