### ISSUE TITLE
[BUG] Cannot get display to look the way I want

### ISSUE THREAD

**Issue by danielbrunt57** [amaximus/garbage-collection-card#98]
**Describe the bug**
I want the two cards to look like this:

![image](https://user-images.githubusercontent.com/49846893/195264346-30b5980b-1f00-46c5-8698-50e1de61c134.png)

But I have to use `hide_date: false` to get `due_txt: true` to work.
```
cards:
  - type: custom:garbage-collection-card
    entity: sensor.garbage
    icon_color: grey
    due_color: red
    due_1_color: yellow
    due_txt: true
    hide_date: false
    hide_days: false
    hide_on_click: false
    icon_size: 30px
    card_mod:
      class: inline-card
  - type: custom:garbage-collection-card
    entity: sensor.recycling
    icon_color: green
    due_color: red
    due_1_color: yellow
    due_txt: true
    hide_date: true
    hide_days: false
    hide_on_click: false
    icon_size: 30px
    card_mod:
      class: inline-card
```
And if I use `hide_date: false` then the display is undesirable when the item is not due tomorrow!

![image](https://user-images.githubusercontent.com/49846893/195264853-065c8231-a69b-49d7-a705-3dd614135709.png)

With `hide_date: true` and `due_txt: true` it looks like this:

![image](https://user-images.githubusercontent.com/49846893/195266778-b1206ae5-bab2-477a-a994-e28981198eb6.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/49846893/195264346-30b5980b-1f00-46c5-8698-50e1de61c134.png)

**Screenshots**

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.20.1
 - Browser: Edge
 - Browser language: US English

**Additional context**
